# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-14 00:41
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCommentByCaption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('caption_query', models.CharField(default='', max_length=200)),
                ('comment_text', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hashtags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hashtag', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_field', models.IntegerField()),
                ('product', models.CharField(default='', max_length=200)),
                ('action', models.CharField(default='', max_length=200)),
                ('text', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='History2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_field', models.IntegerField(default=0)),
                ('date_field', models.DateTimeField(default=0)),
                ('product', models.CharField(default='', max_length=200)),
                ('action', models.CharField(default='', max_length=200)),
                ('text', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Selected_hashtags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_action_date', models.IntegerField(default=0)),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialtune.Hashtags')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('insta_login', models.CharField(max_length=200)),
                ('insta_password', models.CharField(max_length=200)),
                ('twitter_login', models.CharField(blank=True, max_length=200, null=True)),
                ('twitter_password', models.CharField(blank=True, max_length=200, null=True)),
                ('last_post_date', models.DateField(default=datetime.date.today)),
                ('like_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('follow_count', models.IntegerField(default=0)),
                ('unfollow_count', models.IntegerField(default=0)),
                ('hashtags', models.ManyToManyField(through='socialtune.Selected_hashtags', to='socialtune.Hashtags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='selected_hashtags',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialtune.Users'),
        ),
        migrations.AddField(
            model_name='history2',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialtune.Users'),
        ),
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialtune.Users'),
        ),
        migrations.AddField(
            model_name='addcommentbycaption',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialtune.Users'),
        ),
    ]
