# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-14 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialtune', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history2',
            name='user',
        ),
        migrations.DeleteModel(
            name='History2',
        ),
    ]
