# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-17 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialtune', '0004_auto_20170117_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followed_Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_id', models.IntegerField(default=0)),
                ('followed_time', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialtune.Users')),
            ],
        ),
        migrations.RemoveField(
            model_name='history2',
            name='user',
        ),
        migrations.DeleteModel(
            name='History2',
        ),
    ]
