# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-17 00:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialtune', '0007_auto_20170117_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followed_users',
            name='user',
        ),
        migrations.DeleteModel(
            name='Followed_Users',
        ),
    ]
