# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-18 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialtune', '0009_followed_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('num', models.IntegerField(default=0)),
                ('slug', models.CharField(default='', max_length=200)),
                ('last_action_date', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialtune.Users')),
            ],
        ),
    ]
