# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-21 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialtune', '0011_auto_20170120_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='insta_comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='insta_like_count',
            field=models.IntegerField(default=0),
        ),
    ]
