# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-24 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialtune', '0012_auto_20170121_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='like_paused_to',
            field=models.IntegerField(default=0),
        ),
    ]
