# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-29 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialtune', '0013_users_like_paused_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='insta_comments_on',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='users',
            name='insta_follow_on',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='users',
            name='insta_likes_on',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='users',
            name='insta_on',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='users',
            name='insta_unfollow_on',
            field=models.BooleanField(default=True),
        ),
    ]
