# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialtune', '0014_auto_20170129_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Influencers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='insta_who_follow_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='insta_who_followedby_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='insta_who_liked_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='insta_follow_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='influencers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialtune.Users'),
        ),
    ]
