# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialtune', '0016_hashtagforfollow'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='insta_paid_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='insta_time_until',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='insta_trial_active',
            field=models.BooleanField(default=False),
        ),
    ]
